import fs from 'fs-extra';
import Handlebars from 'handlebars';
import os from 'os';
import path from 'path';
import { TContext } from '../lib/context';

export const footerMarkerStart = '<!-- charcoal:footer:start -->';
export const footerMarkerEnd = '<!-- charcoal:footer:end -->';

export const footerTitle = '\n\n\n#### PR Dependency Tree\n\n';
export const footerFooter =
  '\n\nThis tree was auto-generated by [Charcoal](https://github.com/danerwilliams/charcoal)';
export const footerAttribution = 'Auto-generated by charcoal';

export function wrapFooter(footer: string): string {
  return `${footerMarkerStart}${footer}${footerMarkerEnd}`;
}

type TStackEntry = {
  number: number;
  branch: string;
  isCurrent: boolean;
  depth: number;
};

export function createPrBodyFooter(context: TContext, branch: string): string {
  const terminalParent = findTerminalParent(context, branch);
  const entries = collectStack({
    context,
    currentBranches: [terminalParent],
    prBranch: branch,
    currentDepth: 0,
  });

  const customTemplate = readCustomFooterTemplate();

  if (customTemplate) {
    const template = Handlebars.compile(customTemplate);
    return template({
      prs: entries.map((entry, index) => ({
        number: entry.number,
        branch: entry.branch,
        isCurrent: entry.isCurrent,
        position: index + 1,
      })),
      attribution: footerAttribution,
    });
  }

  const tree = entries
    .map(
      (entry) =>
        `\n${'  '.repeat(entry.depth)}* **PR #${entry.number}**${
          entry.isCurrent ? ' 👈' : ''
        }`
    )
    .join('');

  return `${footerTitle}${tree}${footerFooter}`;
}

let cachedTemplate: { path: string; contents: string | undefined } | undefined;

function readCustomFooterTemplate(): string | undefined {
  const configHome =
    process.env.XDG_CONFIG_HOME || path.join(os.homedir(), '.config');
  const templatePath = path.join(configHome, 'charcoal', 'TEMPLATE.md');

  if (cachedTemplate?.path === templatePath) {
    return cachedTemplate.contents;
  }

  const contents = fs.existsSync(templatePath)
    ? fs.readFileSync(templatePath).toString()
    : undefined;

  cachedTemplate = { path: templatePath, contents };
  return contents;
}

function collectStack({
  context,
  currentBranches,
  prBranch,
  currentDepth,
}: {
  context: TContext;
  currentBranches: string[];
  prBranch: string;
  currentDepth: number;
}): TStackEntry[] {
  const entries: TStackEntry[] = [];

  for (const branch of currentBranches) {
    if (branch !== prBranch && !isInStack(context, branch, prBranch)) {
      continue;
    }

    const number = context.engine.getPrInfo(branch)?.number;

    if (number) {
      entries.push({
        number,
        branch,
        isCurrent: branch === prBranch,
        depth: currentDepth,
      });
    }

    const children = context.engine.getChildren(branch);

    if (children.length) {
      entries.push(
        ...collectStack({
          context,
          currentBranches: children,
          prBranch,
          currentDepth: currentDepth + 1,
        })
      );
    }
  }

  return entries;
}

function findTerminalParent(context: TContext, currentBranch: string): string {
  const parent = context.engine.getParent(currentBranch);
  if (!parent) {
    throw new Error('Parent branch is undefined');
  }

  if (context.engine.isTrunk(parent)) {
    return currentBranch;
  }

  return findTerminalParent(context, parent);
}

function isParentOfBranch(
  context: TContext,
  parent: string,
  branch: string
): boolean {
  const children = context.engine.getChildren(parent);

  if (children.includes(branch)) {
    return true;
  }

  for (const child of children) {
    if (isParentOfBranch(context, child, branch)) {
      return true;
    }
  }

  return false;
}

function isInStack(context: TContext, a: string, b: string): boolean {
  return isParentOfBranch(context, a, b) || isParentOfBranch(context, b, a);
}
